name       : zeitgeist
version    : '1.0'
release    : 3
source     :
    - https://launchpad.net/zeitgeist/1.0/1.0/+download/zeitgeist-1.0.tar.xz : 5ff508508f7a7b46acc9fbf1cf73fecb1aec214e18d9d22325aae8c2c2e8ddc8
homepage   : https://launchpad.net/zeitgeist
license    : LGPL-2.1
component  : desktop
summary    : Zeitgeist is a service which logs the users's activities and events (files
    opened, websites visites, conversations held with other people, etc.) and makes
    relevant information available to other applications.
description: |
    Zeitgeist is a service which logs the users's activities and events (files opened, websites visites, conversations held with other people, etc.) and makes relevant information available to other applications.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libffi)
    - pkgconfig(libpcre)
    - pkgconfig(raptor2)
    - pkgconfig(sqlite3)
    - pkgconfig(telepathy-glib)
    - pkgconfig(xapian-core)
    - rdflib
    - vala
replaces   :
    - libzeitgeist
    - devel : libzeitgeist-devel
setup      : |
    %configure --disable-static \
        --enable-datahub \
        --enable-fts
build      : |
    %make
install    : |
    %make_install
