name       : zeitgeist
version    : 1.0.4
release    : 16
source     :
    - https://launchpad.net/zeitgeist/1.0/1.0.4/+download/zeitgeist-1.0.4.tar.xz : da0e11160b2a36fe6260acf62b4190e29755fd5df130818157a04883c1eb7237
homepage   : https://launchpad.net/zeitgeist
license    : LGPL-2.1-or-later
component  : desktop
summary    : A service which logs the users's activities and events
description: |
    Zeitgeist is a service which logs the users's activities and events (files opened, websites visites, conversations held with other people, etc.) and makes relevant information available to other applications.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libffi)
    - pkgconfig(libpcre)
    - pkgconfig(raptor2)
    - pkgconfig(sqlite3)
    - pkgconfig(telepathy-glib)
    - pkgconfig(xapian-core)
    - rdflib
    - vala
replaces   :
    - libzeitgeist
    - devel : libzeitgeist-devel
environment: |
    export PYTHON=python3
setup      : |
    %configure --disable-static --enable-datahub --enable-fts
build      : |
    %make
install    : |
    %make_install
